# Generated by Django 5.2.4 on 2025-11-24 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('general', 'عام'), ('governance', 'حوكمة'), ('technical', 'تقني'), ('marketing', 'تسويق'), ('social_research', 'البحث الاجتماعي'), ('projects', 'المشاريع'), ('volunteering', 'التطوع')], max_length=50, verbose_name='القسم الخاص بالإنجاز')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الإنجاز')),
                ('description', models.TextField(verbose_name='تفاصيل الإنجاز')),
                ('achievement_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('display_in_report', models.BooleanField(default=True, verbose_name='عرض الإنجاز في التقرير السنوي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements_created', to=settings.AUTH_USER_MODEL, verbose_name='المُنشئ')),
            ],
            options={
                'verbose_name': 'إنجاز',
                'verbose_name_plural': 'الإنجازات',
                'ordering': ['-created_at'],
                'permissions': [('can_view_all_achievements', 'يمكنه عرض جميع الإنجازات'), ('can_edit_all_achievements', 'يمكنه تعديل جميع الإنجازات'), ('can_delete_all_achievements', 'يمكنه حذف جميع الإنجازات')],
            },
        ),
        migrations.CreateModel(
            name='AchievementLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(max_length=500, verbose_name='رابط المحتوى أو الملفات')),
                ('link_title', models.CharField(blank=True, max_length=255, verbose_name='عنوان الرابط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='annualreport.achievement', verbose_name='الإنجاز')),
            ],
            options={
                'verbose_name': 'رابط إنجاز',
                'verbose_name_plural': 'روابط الإنجازات',
                'ordering': ['created_at'],
            },
        ),
    ]
