# Generated by Django 5.2.4 on 2025-07-06 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم المشروع', max_length=200, verbose_name='اسم المشروع')),
                ('description', models.TextField(blank=True, help_text='وصف تفصيلي للمشروع', verbose_name='وصف المشروع')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد التنفيذ'), ('finished', 'مكتمل')], default='new', help_text='الحالة الحالية للمشروع', max_length=20, verbose_name='حالة المشروع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('assigned_employee', models.ForeignKey(blank=True, help_text='الموظف المسؤول عن المشروع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المُعيّن')),
                ('created_by', models.ForeignKey(help_text='الموظف الذي أنشأ المشروع', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المشروع')),
            ],
            options={
                'verbose_name': 'مشروع',
                'verbose_name_plural': 'المشاريع',
                'ordering': ['-created_at'],
            },
        ),
    ]
