# Generated by Django 5.2.4 on 2025-07-06 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='assigned_employee',
        ),
        migrations.AddField(
            model_name='project',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, help_text='الموظفين المسؤولين عن المشروع', related_name='assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='الموظفين المُعيّنين'),
        ),
        migrations.AddField(
            model_name='project',
            name='primary_assigned_employee',
            field=models.ForeignKey(blank=True, help_text='الموظف الرئيسي المسؤول عن المشروع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_assigned_projects', to=settings.AUTH_USER_MODEL, verbose_name='الموظف الرئيسي'),
        ),
        migrations.AlterField(
            model_name='project',
            name='due_date',
            field=models.DateField(blank=True, help_text='التاريخ المتوقع لإنجاز المشروع', null=True, verbose_name='تاريخ الانتهاء'),
        ),
    ]
