# Generated by Django 5.2.4 on 2025-07-06 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_project_assigned_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم المهمة', max_length=200, verbose_name='اسم المهمة')),
                ('detail', models.TextField(blank=True, help_text='وصف تفصيلي للمهمة', verbose_name='تفاصيل المهمة')),
                ('due_date', models.DateField(blank=True, help_text='التاريخ المتوقع لإنجاز المهمة', null=True, verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('finished', 'مكتمل')], default='new', help_text='الحالة الحالية للمهمة', max_length=20, verbose_name='حالة المهمة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تحديث')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='الموظف المُعيّن للمهمة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='مُعيّن إلى')),
                ('created_by', models.ForeignKey(help_text='الموظف الذي أنشأ المهمة', on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='منشئ المهمة')),
                ('project', models.ForeignKey(blank=True, help_text='المشروع المرتبط بالمهمة', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهام',
                'ordering': ['-created_at'],
            },
        ),
    ]
