# Generated by Django 5.2.4 on 2025-07-07 08:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'يناير'), (2, 'فبراير'), (3, 'مارس'), (4, 'أبريل'), (5, 'مايو'), (6, 'يونيو'), (7, 'يوليو'), (8, 'أغسطس'), (9, 'سبتمبر'), (10, 'أكتوبر'), (11, 'نوفمبر'), (12, 'ديسمبر')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('year', models.IntegerField(default=2025, validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2050)], verbose_name='السنة')),
                ('goals', models.TextField(help_text='أهداف الموظف لهذا الشهر', verbose_name='الأهداف')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_goals', to=settings.AUTH_USER_MODEL, verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'هدف شهري',
                'verbose_name_plural': 'الأهداف الشهرية',
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
