# Generated by Django 5.2.4 on 2025-07-09 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_add_notification_models'),
        ('tasks', '0004_monthlygoal'),
    ]

    operations = [
    ]
