# Generated by Django 5.2.4 on 2025-07-09 06:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_merge_0002_add_notification_models_0004_monthlygoal'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailnotificationlog',
            new_name='tasks_email_recipie_388802_idx',
            old_name='tasks_email_recipie_48b7e4_idx',
        ),
        migrations.RenameIndex(
            model_name='emailnotificationlog',
            new_name='tasks_email_status_f70351_idx',
            old_name='tasks_email_status_a5c542_idx',
        ),
        migrations.RenameIndex(
            model_name='emailnotificationlog',
            new_name='tasks_email_task_id_7ddcab_idx',
            old_name='tasks_email_task_id_89e2f1_idx',
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='digest_time',
            field=models.TimeField(default=datetime.time(9, 0, 33, 857564), verbose_name='وقت إرسال الملخص اليومي'),
        ),
    ]
